name: Build C++ Packages

  #on: [push, pull_request]

on: pull_request

jobs:
  build:

    #    runs-on: ubuntu-latest

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: versiondump arm gcc version
      run: cat /etc/lsb-release
 
    - name: Install cross compile toolchain
      run: sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf libspdlog-dev
    
    - name: Install libraries
      run: sudo apt-get install libspdlog-dev libpcap-dev libevdev2 libev-dev protobuf-compiler 

    - name: dump arm gcc version
      run: arm-linux-gnueabihf-gcc -v
      working-directory: ./src/raspberrypi
 
    - name: dump native gcc version
      run: gcc -v
      working-directory: ./src/raspberrypi
 

    - name: make standard
      run: make all -j6 CONNECT_TYPE=STANDARD CROSS_COMPILE=arm-linux-gnueabihf-
      working-directory: ./src/raspberrypi
 
    - name: make fullspec
      run: make all -j6 CONNECT_TYPE=FULLSPEC CROSS_COMPILE=arm-linux-gnueabihf-
      working-directory: ./src/raspberrypi

    # We need to tar the binary outputs to retain the executable
    # file permission. Currently, actions/upload-artifact only
    # supports .ZIP files.
    # This is workaround for https://github.com/actions/upload-artifact/issues/38
    - name: tar binary outputs
      run: tar -czvf rascsi.tar.gz ./bin
      working-directory: ./src/raspberrypi

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arm-binaries
        path: ./src/raspberrypi/rascsi.tar.gz

#  buildroot-image:
#    runs-on: ubuntu-latest
#    steps:
#      - name: git-fetch buildroot
#        run: git clone git://git.busybox.net/buildroot
#      - name: make defconfig
#        run: make raspberrypi4_defconfig
#        working-directory: ./buildroot
#      - name: make
#        run: make all
#        working-directory: ./buildroot
